services:
  mysql_db:
    container_name: mysql_db_station
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: utilisateur
      MYSQL_USER: lilian
      MYSQL_PASSWORD: mysecret
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - ./script/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

  spring_app:
    container_name: spring_station
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/utilisateur?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: lilian
      SPRING_DATASOURCE_PASSWORD: mysecret
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8087:8087"
    networks:
      - mynetwork

volumes:
  mysql_data:
    driver: local

networks:
  mynetwork:
