SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `station` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `station`;
-- --------------------------------------------------------

CREATE TABLE `station` (
   `stationId` BIGINT NOT NULL AUTO_INCREMENT,
   `position` VARCHAR(255) NOT NULL,
   `nbPlaces` BIGINT NOT NULL,
   `nbPlacesTaken` BIGINT DEFAULT NULL,
   `nbPlacesFree` BIGINT DEFAULT NULL,
   PRIMARY KEY (`stationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

